### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by WhitewaterDave** [ilscipio/scipio-erp#14]
When I use the installer to install ScipioERP on MacOS, it says that I have to install Java and set JAVA_HOME. They are set. I got this error on my MacBook and my Mac Pro. Java is installed and JAVA_HOME is set on both. Any suggestions other than downloading the Git repository?
Regards

![Screen Shot 2019-04-07 at 9 11 41 AM](https://user-images.githubusercontent.com/8185773/55684100-8611a780-5915-11e9-9553-8c1aab17a239.png)

**Comment by martinbehrens** [comment]
Hi @WhitewaterDave and good catch, there indeed is an issue. Until we have it fixed, please just execute:

`/Volumes/ScipioERP/Scipio\ ERP\ Installer.app/Contents/MacOS/JavaApplicationStub`

in a shell instead of clicking the installer icon. Thank you!

**Comment by WhitewaterDave** [comment]
Thank you for your quick response. I was able to successfully install and start the application with the instructions you provided. Thanks for the help.
