### ISSUE TITLE
scipio, still run?

### ISSUE THREAD

**Issue by punkyard** [ilscipio/scipio-erp#23]
hi
is scipio project still on-going?

**Comment by pplx** [comment]
Hello. Yes it is! We will be releasing a new milestone in the upcoming months or sooner. Thank you for your interest and let us know if you have specific questions.

**Comment by punkyard** [comment]
cool
thanks

**Comment by punkyard** [comment]
it says to install Java 1.8 (or greater) SDK

but i can't find anything on the web on how to install SDK on ubuntu, only JDK, JRE, JVM
can you lead me please?

**Comment by pplx** [comment]
JDK 11 is recommended. On Ubuntu/Debian:

`apt install openjdk-11-jdk openjdk-11-jdk-headless`
