### ISSUE TITLE
how to cluster deploy?

### ISSUE THREAD

**Issue by hanyou** [ilscipio/scipio-erp#3]
I want to deploy several instance to cluster, how to do?

**Comment by madppiper** [comment]
Hi hanyou, 

I will write a small article for our documentation and leave the link here in a few minutes.

Cheers,
Paul

**Comment by madppiper** [comment]
I added the following article to our developer documentation: 

http://www.scipioerp.com/community/developer/installation-configuration/clustering/

Let me know if this works for you.

**Comment by hanyou** [comment]
if need share session, how to do? can we put session in redis?

**Comment by madppiper** [comment]
I am not sure what you mean by "redis", but generally speaking we do not recommend to use the tomcat based session sharing. We do not know if it works and despite, it adds no benefit to your setup. Using "sticky sessions" will force a user to stay on the same server once he opens a request for the entirety of the session. If his sessions ends, or if another user accesses your cluster, it is possible that he will access a different machine for their respective session. So if you want to run in a cluster and do not want to worry about whether or not a user session is always in the right condition, then sticky sessions are the way to go.

A [Webserver](https://en.wikipedia.org/wiki/Web_server) is a piece of software that handles incoming requests from the internet. "Apache" or "nginx" are good examples for this. The are many reasons as to why you should consider adding a webserver infront of a clustered application setup. In the context here, it is to handle sticky sessions (and other things, like ssl, reverse-proxy of urls and so on).

So the way the article describes a cluster setup is really our recommendation. If despite my absolute warning against shared sessioning you still want to use it, then you can enable it by uncommenting lines 48-65 in \framework\catalina\ofbiz-component.xml. Like I said though, you will be on your own then ;)

**Comment by martinbehrens** [comment]
@hanyou We haven't had Scipio ERP in production with Redis, yet.

**Comment by hanyou** [comment]
Thank @madppiper , i use Nginx in front of SCIPIO.
Can i change ActiveMQ to RabbitMQ?
