### ISSUE TITLE
AP invoice creation error

### ISSUE THREAD

**Issue by joskar201** [ilscipio/scipio-erp#8]
On clicking the new invoice button in accounts payable (Accounts payable -> Invoices -> new invoice) I get (The Following Errors Occurred
org.ofbiz.webapp.control.RequestHandlerException: Unknown request [null]; this request does not exist or cannot be called directly.).
 How can I fix this? 
Thanks in advance.

**Comment by madppiper** [comment]
Hey Joskar201,

I cannot reproduce this happening on the demo server, see:

https://ce.scipioerp.com/accounting/control/newInvoice

What version of Scipio ERP are you using?

**Comment by madppiper** [comment]
I also checked the logs - this has not been an issue for at least a year that could effect the behavior. So you may just be running an outdated version. Please update your local version and retry. I will close this ticket for now. Please let me know if this is still an issue after the update and we can reopen the issue.

**Comment by madppiper** [comment]
You were right - I was looking at the wrong screens. I will commit a bugfix for you.

**Comment by madppiper** [comment]
I committed a fix in 525b39c5. This must have been an oversight from the larger updates the module received a year ago. The fix will be pushed to github later today. I will close this ticket afterwards. 



Thanks again for noticing!

**Comment by madppiper** [comment]
A fix has been pushed an hour ago. Closing the issue
