### ISSUE TITLE
Multiple User login at the same at several computers!

### ISSUE THREAD

**Issue by okethoxhaucx** [ilscipio/scipio-erp#9]
Good Afternoon! Im writing to you, to let you know that we need the feature for the user to be logged in at several places, without interfering one another while the login is performed. This is available at most of web applications. For example, If I am logged in at two different computers with the same user, if I logout from the user at one of the computer, the logout will be performed also at the other computers. We need the feature for letting a user to be logged in at several computers at the same time.

**Comment by madppiper** [comment]
Discussion moved to Scipio Extranet: https://gitlab.ilscipio.com/ucxchange/ucx-doc/issues/1
